# Generated by Django 5.2.1 on 2025-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='consistency_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_5_matches_form',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='opposition_performance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='venue_performance',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
